### ISSUE TITLE
Legacy Noon vs Indicative Rate

### ISSUE THREAD

**Issue by kevmitch** [tsiemens/acb#1]
https://github.com/tsiemens/acb/blob/3b01de49e0290bda01b9eb05133ebe3d2ef14bd0/fx/io.go#L19

While `IEXE0101` (the noon rate) certainly used to be the correct value to use (see [Desjardins](https://www.disnat.com/en/learning/expert-articles/patric-saint-onge/which-exchange-rate-to-use-for-transactions-made-in-2015), and [The Globe and Mail](https://www.theglobeandmail.com/globe-investor/investor-education/calculating-gains-and-losses-on-us-stocks-part-2/article28747713/)), this value only exists up to 2017-04-28.

The Bank of Canada now uses a new "[Indicative Rate](https://www.bankofcanada.ca/2017/05/calculation-methodology-foreign-exchange-rates/)", represented by `FXUSDCAD`. See also the [Financial Post](http://business.financialpost.com/news/fp-street/say-goodbye-to-the-bank-of-canadas-noon-exchange-rate-say-hello-to-indicative-rate).

The `FXUSDCAD` goes back as far as 2017-01-03. IANAA, but I'm going with this value for the whole of 2017. You could alternatively reasonably argue that you should use `IEXE0101` until it stops working and then switch over to `FXUSDCAD`, but given the way you've divided it up into years here, the former seems to make more sense.

**Comment by tsiemens** [comment]
Ah, yes this. Did not spend enough time reading up on why I ran into this.

Had been using `FXUSDCAD`, and then found that it returned no results for 2016 (as you mentioned), so I switched everything to `IEXE0101`. Makes sense to have <= 2016 use `IEXE0101` and >= 2017  use `FXUSDCAD`
