### ISSUE TITLE
No "-f" option for readline on OSX

### ISSUE THREAD

**Issue by aftabn** [tsiemens/acb#3]
Running any of the make commands will fail because of the first line in the Makefile:
`export GOPATH=$(shell echo $$(readlink -f $$(pwd)/../../../..))`
because readline in OSX doesn't have a -f option.

Workaround was to replace `readline` with `greadline` after running `brew install coreutils`

**Comment by tsiemens** [comment]
Probably will write a local script which should be more portable. python might be a good choice, and has some options.

For reference: https://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac

**Comment by tsiemens** [comment]
Did everyone one better, and recommend standard procedure for installation.

Fixed in e57f90e
